---
branches:
  only:
  - master
  - devel
  - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

clone_depth: 2

environment:
  matrix:
  -  CONDA_ROOT: "C:\\Miniconda37-x64"
     TOXENV: "safety,py37"
  -  CONDA_ROOT: "C:\\Miniconda38-x64"
     TOXENV: "safety,py38"

matrix:
  fast_finish: true

cache:
- '%LOCALAPPDATA%\pip\Cache'

platform: x64

build: off

install:
- set PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%
- conda info
- python --version
- python -m pip install --upgrade --disable-pip-version-check pip setuptools wheel tox

test_script:
- tox

notifications:
- provider: Email
  on_build_success: false
  on_build_failure: true
