name: Cron Test

on:
  schedule:
  # Run every Tuesday at 11:00.
  - cron: '0 11 * * 2'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install tox tox-gh-actions
    - name: Check requirements with pip
      run: python -m pip check .
    - name: Test isort
      run: tox -e isort
      if: matrix.python-version == '3.6'
    - name: Test black
      run: tox -e black
      if: matrix.python-version == '3.6'
    - name: Test flake8
      run: tox -e flake8
      if: matrix.python-version == '3.6'
    - name: Test docs
      run: tox -e docs
      if: matrix.python-version == '3.6'
    - name: Test safety
      run: tox -e safety
    - name: Test suite
      run: tox -- --cov-report=xml
      env:
        SECRET_WORKSPACE_ID: ${{ secrets.STRUCTURIZR_WORKSPACE_ID }}
        SECRET_API_KEY: ${{ secrets.STRUCTURIZR_API_KEY }}
        SECRET_API_SECRET: ${{ secrets.STRUCTURIZR_API_SECRET }}
