name: CD

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox tox-gh-actions twine
      - name: Test with tox
        run: tox
        env:
          SECRET_WORKSPACE_ID: ${{ secrets.STRUCTURIZR_WORKSPACE_ID }}
          SECRET_API_KEY: ${{ secrets.STRUCTURIZR_API_KEY }}
          SECRET_API_SECRET: ${{ secrets.STRUCTURIZR_API_SECRET }}
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Check the package
        run: twine check dist/*
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run:
          twine upload --skip-existing --non-interactive dist/*
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: >
            Please see
            https://github.com/${{ github.repository }}/blob/${GITHUB_REF#refs/heads/}/CHANGELOG.rst
            for the full release notes.
          draft: false
          prerelease: false
